name: citibike-analysis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - pyarrow
  - numpy
  - geopandas
  - shapely
  - pyproj
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - requests
